# -*- coding: utf-8 -*-
"""AmaliTech Capstone Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBOmrUpT_MwHgUfgrFIrgN0WRWWpZO47

# **Project Brief: The "*Sugar Trap*" Market Gap Analysis**

### What I'm Building
I am working as a data analyst for Helix CPG Partners, a strategic food and beverage consultancy. The client is a global snack manufacturer preparing to launch a new healthy snacking product line.

The core business problem is that the client believes the snack market is oversaturated with high-sugar, high-fat products, but they need data to prove it, and more importantly, to identify exactly where the gaps are.

## **Story 1: Data Ingestion & "The Clean Up"**

Cleaning the dataset that removes products with erroneous nutritional information, so that my analysis is not skewed by bad data entry.
"""

# libraries and modules needed for the project
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import re

#downloading the Open Food Facts dataset
!wget https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz

os.listdir()

# reading the csv file and correctly resetting the index outside the function call
food_data = pd.read_csv("en.openfoodfacts.org.products.csv.gz", header=0, sep='\t', nrows=500000, low_memory=False)

food_data

# displaying all the columns in the dataset to be able to select the needed categories
food_data.columns

for column in food_data.columns:
  print(column)

columns = [
    'product_name',
    'brands',
    'categories_en',
    'categories_tags',
    'main_category_en',
    'pnns_groups_1',
    'pnns_groups_2',
    'countries_en',
    'sugars_100g',
    'fat_100g',
    'saturated-fat_100g',
    'proteins_100g',
    'fiber_100g',
    'carbohydrates_100g',
    'salt_100g',
    'energy-kcal_100g',
    'nutriscore_score',
    'nutriscore_grade',
    'nova_group',
    'unique_scans_n',
    'ingredients_text',
]

food_data = food_data[columns]
food_data

# removing rows with missing values
food_data = food_data.dropna(subset=[
    'product_name',
    'sugars_100g',
    'fat_100g',
    'saturated-fat_100g',
    'proteins_100g',
    'fiber_100g',
    'carbohydrates_100g',
    'salt_100g',
    'energy-kcal_100g',
])

#removing rows where product_name is empty
food_data = food_data[food_data['product_name'].str.strip() != ""]

#keeping only nutritional values (0–100g per 100g)
food_data = food_data[
    (food_data['sugars_100g'].between(0, 100)) &
    (food_data['proteins_100g'].between(0, 100)) &
    (food_data['fat_100g'].between(0, 100)) &
    (food_data['fiber_100g'].between(0, 100)) &
    (food_data['carbohydrates_100g'].between(0, 100)) &
    (food_data['salt_100g'].between(0, 100)) &
    (food_data['saturated-fat_100g'].between(0, 100))
]

food_data

food_data.describe()

food_data.info()

"""## **Story 2: The Category Wrangler**

Grouping products into readable high-level categories, so that I don't have to look at 10,000 unique, messy tags.
"""

#filliing the NaN values in the categories_en  with an empty string to avoid errors during string operations
food_data['categories_en'] = food_data['categories_en'].fillna('')

#showing the different category tags
food_data['categories_tags'].unique()

# the categories function takes the category tags of a product and maps them to a simplified classification
def categories(category_tags):
    # converts the input to a lowercase string to ensure consistent keyword matching across the dataset
    tags = str(category_tags).lower()

    # snack sub categories
    if 'chocolate' in tags or 'chocolat' in tags:
        return 'Chocolate'

    elif any(tag in tags for tag in ['chips', 'crisps', 'popcorn', 'pretzel', 'crackers', 'tortilla', 'nachos']):
        return 'Chips & Crisps'

    elif any(tag in tags for tag in ['salty', 'salted', 'craquelins', 'appetizers']):
        return 'Salty Snacks'

    elif any(tag in tags for tag in ['cookie', 'biscuit', 'wafer', 'cake', 'muffin', 'pastry', 'madeleine', 'viennoiseries', 'doughnut', 'dessert', 'pie', 'sweet-snacks']):
        return 'Cookies & Cakes'

    elif any(tag in tags for tag in ['granola', 'protein-bar', 'energy-bar', 'cereal-bar', 'protein-shake', 'proteiques', 'supplement', 'whey', 'bars']):
        return 'Bars & Granola'

    elif any(tag in tags for tag in ['nut', 'seed', 'peanut', 'almond', 'cashew', 'walnut', 'pistachio', 'trail mix', 'arachide', 'trail-mix']):
        return 'Nuts & Seeds'

    elif any(tag in tags for tag in ['confectionery', 'bonbon', 'candy', 'caramel', 'fudge', 'marshmallow', 'licorice', 'confectioneries', 'candies', 'gummi-candies']):
        return 'Candies & Sweets'

    elif any(tag in tags for tag in ['beverage', 'drink', 'juice', 'water', 'coffee', 'tea', 'soda', 'cola']):
        return 'Beverages'

    elif any(tag in tags for tag in ['dairy', 'milk', 'cheese', 'yogurt', 'yaourt', 'pudding', 'skyr', 'mousse', 'ice-cream', 'dairies', 'creams']):
        return 'Dairy'

    elif any(tag in tags for tag in ['fruit', 'vegetable', 'plant-based', 'legume', 'compote', 'apricot', 'date', 'raisins', 'prugne']):
        return 'Fruits, Vegetables & Legumes'

    elif any(tag in tags for tag in ['grain', 'bread', 'pasta', 'rice', 'cereal', 'flour']):
        return 'Grains & Baked Goods'

    elif any(tag in tags for tag in ['meat', 'poultry', 'fish', 'seafood', 'beef', 'chicken', 'pork']):
        return 'Meat & Seafood'

    elif any(tag in tags for tag in ['meal', 'prepared', 'pizza', 'soup', 'stew', 'ravioli', 'burger', 'sandwich', 'burrito', 'tamales', 'mexican-dinner-mixes']):
        return 'Prepared Meals'

    elif any(tag in tags for tag in ['oil', 'fat', 'butter', 'margarine']):
        return 'Fats & Oils'

    elif any(tag in tags for tag in ['sauce', 'spice', 'condiment', 'ketchup', 'mustard', 'pesto', 'syrup', 'sweetener', 'honey', 'spreads', 'tapenade', 'salsa']):
        return 'Sauces & Spices'

    else:
        return 'Other Snacks'

#applying the cleaned categorization logic using the renamed function
food_data['primary_category'] = food_data['categories_tags'].apply(categories)

food_data['primary_category'].value_counts().sort_index()

food_data[['product_name', 'primary_category']].head(10)

#visualizing the distribution of the categories
plt.figure(figsize=(12, 6))
sns.countplot(
    data=food_data,
    y='primary_category',
    order=food_data['primary_category'].value_counts().index,
    hue='primary_category',
    palette='viridis',
    legend=False
)

plt.title('Product Distribution by Refined Category', fontsize=16)
plt.xlabel('Number of Products', fontsize=12)
plt.ylabel('Category', fontsize=12)
plt.tight_layout()
plt.show()

"""## **Story 3: The "Nutrient Matrix" Visualization**

Creating a scatter Plot comparing Sugar (X-axis) vs. Protein (Y-axis) for different categories, so that I can visually spot where the products are clustered.
"""

# defining the target segments with lower-case variable names
low_sugar_threshold = 10
high_protein_threshold = 15

plt.figure(figsize=(14, 8))
sns.set_theme(style='whitegrid')

#creaating scatter plot
scatter = sns.scatterplot(
    data=food_data,
    x='sugars_100g',
    y='proteins_100g',
    hue='primary_category',
    alpha=0.6,
    edgecolor=None,
    palette='viridis'
)

#highlighting the empty quadrant (High Protein + Low Sugar)
plt.axvspan(0, low_sugar_threshold, color='green', alpha=0.1, label='Low Sugar Target')
plt.axhspan(high_protein_threshold, 100, color='blue', alpha=0.1, label='High Protein Target')

plt.text(1, 90, "'BLUE OCEAN' GAP:\nHigh Protein (>15g) & Low Sugar (<10g)",
         fontsize=12, color='darkgreen', fontweight='bold',
         bbox=dict(facecolor='white', alpha=0.7))

plt.title('Nutrient Matrix Gap Analysis', fontsize=16)
plt.xlabel('Sugar (g per 100g)', fontsize=12)
plt.ylabel('Protein (g per 100g)', fontsize=12)
plt.xlim(-2, 100)
plt.ylim(-2, 100)
plt.legend(title='Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

#calculating the stats
total_products = food_data[(food_data['sugars_100g'] < 10) & (food_data['proteins_100g'] > 15)]

print(f"Total products found in the 'Blue Ocean' quadrant: {len(total_products)}")

print("\nTop categories currently occupying this space:")
display(total_products['primary_category'].value_counts())

print("\nSample products in the target gap:")
display(total_products[['product_name', 'brands', 'sugars_100g', 'proteins_100g']].head(10))

# creating a market summary table with average sugar and protein metrics
category_nutrient_summary = food_data.groupby('primary_category').agg({'sugars_100g': 'mean','proteins_100g': 'mean','product_name': 'count'}).rename(columns={'sugars_100g': 'Avg Sugar (g)','proteins_100g': 'Avg Protein (g)','product_name': 'Total Count'}).sort_values(by='Avg Protein (g)', ascending=False)

# calculating Saturation_Score and add it to the summary table
category_nutrient_summary['Saturation_Score'] = (
    category_nutrient_summary['Total Count'] / category_nutrient_summary['Total Count'].max() * 0.7 +
    category_nutrient_summary['Avg Sugar (g)'] / 100 * 0.3
)

# displaying the styled benchmark table with the new saturation score
category_nutrient_summary.style.background_gradient(cmap='RdYlGn_r', subset=['Avg Sugar (g)']).background_gradient(cmap='RdYlGn', subset=['Avg Protein (g)']).background_gradient(cmap='viridis_r', subset=['Saturation_Score'])

"""The saturation score was introduced to quantify market opportunity by combining product count and average sugar content into a single metric. This helps in identifying categories that are less saturated and potentially have higher growth potential for new, healthier products. It gives a more holistic view beyond just individual nutrient levels, providing strategic insight into market gaps.

## **Story 4: The Recommendation**

My recommendation on what product the client should build.

**Strategic Recommendation for Helix CPG Partners:**

Based on the data derived from the Nutrient Matrix Gap Analysis in Story 3 and the Category Nutrient Summary Table, the biggest market opportunity is in Salty Snacks (specifically savory protein bars or high-protein crisps), specifically targeting products with more than 15g of protein and less than 10g of sugar.

## **5. Bonus User Story: The "Hidden Gem"**
"""

# focusing on the 'High Protein' data defined earlier
high_protein = food_data[(food_data['proteins_100g'] > 15) & (food_data['sugars_100g'] < 10)]

# cleaning and flattening the ingredients text
ingredients_list = high_protein['ingredients_text'].dropna().str.lower()

# defining common protein sources to search for
protein_keywords = ['soy', 'soja', 'whey', 'lactoserum', 'milk', 'lait', 'egg', 'oeuf', 'peanut', 'cacahuete', 'almond', 'amande', 'pea ', 'pois', 'lentil', 'lentille', 'chickpea', 'pois chiche', 'wheat gluten', 'seitan', 'casein', 'beef', 'chicken', 'poulet', 'fish', 'poisson']

found_sources = []
for text in ingredients_list:
    for source in protein_keywords:
        if source in text:
            found_sources.append(source)

# dictionary counting without Counter
counts_dict = {}
for item in found_sources:
    if item in counts_dict:
        counts_dict[item] += 1
    else:
        counts_dict[item] = 1

#convert to list of [count, name] and sort
sorting_list = []
for name, count in counts_dict.items():
    sorting_list.append([count, name])

# sort descending by count
sorting_list.sort(reverse=True)

#extractin top sources
top_sources = []
for i in range(min(3, len(sorting_list))):
    count, name = sorting_list[i]
    top_sources.append((name, count))

print("Top 3 Common Protein Sources in the High Protein Data:")
rank = 1
for item in top_sources:
    source = item[0]
    count = item[1]
    print(f"{rank}. {source.strip().upper()} (found in {count} products)")
    rank += 1

# visual representation
plt.figure(figsize=(10, 5))
top_data = sorting_list[:10]
frequencies = [item[0] for item in top_data]
sources = [item[1] for item in top_data]

sns.barplot(x=frequencies, y=sources, hue=sources, palette='magma', legend=False)
plt.title('Common Protein Sources found in High-Protein/Low-Sugar Products')
plt.xlabel('Frequency of Mention')
plt.show()

"""## **6. The "Candidate's Choice" Challenge**

**Why I added this:**

I chose this because Sugar vs. Protein shows one dimension of health but the Nutriscore grade captures the full nutritional picture i.e sugar, fat, salt, fiber, and protein etc combined into one A to E score. Therefore, category full of D and E grades represents a larger Blue Ocean opportunity for disruption.
"""

# only rows with a valid nutriscore grade
nutriscore_data = food_data[food_data['nutriscore_grade'].isin(['a', 'b', 'c', 'd', 'e'])].copy()

# standardize grades for display
nutriscore_data['nutriscore_grade'] = nutriscore_data['nutriscore_grade'].str.upper()

# counting only products per category per grade
grade_counts = nutriscore_data.groupby(['primary_category', 'nutriscore_grade']).size().reset_index(name='product_count')

# filtering for categories with significant data (Total > 50 graded products)
category_totals = grade_counts.groupby('primary_category')['product_count'].sum()
significant_categories = category_totals[category_totals > 50].index
grade_counts = grade_counts[grade_counts['primary_category'].isin(significant_categories)]

# grouped bar chart using Matplotlib/Seaborn
import matplotlib.pyplot as plt
import seaborn as sns

# Set default style for consistency
sns.set_theme(style='whitegrid')

# Create a figure and axes
plt.figure(figsize=(14, 8))

# Plot the grouped bar chart
sns.barplot(
    data=grade_counts,
    x='primary_category',
    y='product_count',
    hue='nutriscore_grade',
    palette={'A': '#038141', 'B': '#85BB2F', 'C': '#FECB02', 'D': '#EE8100', 'E': '#E63E11'},
    order=grade_counts['primary_category'].unique() # Maintain category order
)

plt.title('Nutriscore Grade Distribution by Category', fontsize=16)
plt.xlabel('Category', fontsize=12)
plt.ylabel('Number of Products', fontsize=12)

# Add legend for Nutriscore Grades
plt.legend(title='Grade', bbox_to_anchor=(1.05, 1), loc='upper left')

# Add significance text as an annotation
significance_text = (
    "Grade Key:\n"
    "A: Best Quality\n"
    "B: Good Quality\n"
    "C: Average\n"
    "D: Lower Quality\n"
    "E: Poorest Quality"
)
plt.text(1.02, 0.5, significance_text, transform=plt.gca().transAxes, fontsize=10, verticalalignment='center', bbox=dict(facecolor='white', alpha=0.7, edgecolor='black'))

plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for readability
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

#  the percentage of unhealthy (D/E) grades for ALL categories
total_per_category = nutriscore_data.groupby('primary_category').size().reset_index(name='total')
bad_per_category = nutriscore_data[nutriscore_data['nutriscore_grade'].isin(['D', 'E'])].groupby('primary_category').size().reset_index(name='bad_count')

full_health_summary = total_per_category.merge(bad_per_category, on='primary_category', how='left').fillna(0)
full_health_summary['pct_unhealthy'] = (full_health_summary['bad_count'] / full_health_summary['total'] * 100).round(1)

#srting by the highest percentage of unhealthy products to highlight opportunity areas
full_health_summary = full_health_summary.sort_values('pct_unhealthy', ascending=False)

full_health_summary[['primary_category', 'total', 'pct_unhealthy']]

!jupyter nbconvert --to html /content/AmaliTech_Capstone_Project.ipynb